//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitecore.Feature.SalesForceIntegration.Website.sfgoal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GoalWebServiceBinding", Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public partial class GoalWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SessionHeader sessionHeaderValueField;
        
        private CallOptions callOptionsValueField;
        
        private DebuggingHeader debuggingHeaderValueField;
        
        private AllowFieldTruncationHeader allowFieldTruncationHeaderValueField;
        
        private DebuggingInfo debuggingInfoValueField;
        
        private System.Threading.SendOrPostCallback addGoalEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GoalWebServiceService() {
            this.Url = global::Sitecore.Feature.SalesForceIntegration.Website.Properties.Settings.Default.Sitecore_Feature_SalesForceIntegration_Website_sfgoal_GoalWebServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public CallOptions CallOptionsValue {
            get {
                return this.callOptionsValueField;
            }
            set {
                this.callOptionsValueField = value;
            }
        }
        
        public DebuggingHeader DebuggingHeaderValue {
            get {
                return this.debuggingHeaderValueField;
            }
            set {
                this.debuggingHeaderValueField = value;
            }
        }
        
        public AllowFieldTruncationHeader AllowFieldTruncationHeaderValue {
            get {
                return this.allowFieldTruncationHeaderValueField;
            }
            set {
                this.allowFieldTruncationHeaderValueField = value;
            }
        }
        
        public DebuggingInfo DebuggingInfoValue {
            get {
                return this.debuggingInfoValueField;
            }
            set {
                this.debuggingInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addGoalEventCompletedEventHandler addGoalEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DebuggingInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AllowFieldTruncationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DebuggingHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.sforce.com/schemas/class/GoalWebService", ResponseNamespace="http://soap.sforce.com/schemas/class/GoalWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public Response addGoalEvent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Request req) {
            object[] results = this.Invoke("addGoalEvent", new object[] {
                        req});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void addGoalEventAsync(Request req) {
            this.addGoalEventAsync(req, null);
        }
        
        /// <remarks/>
        public void addGoalEventAsync(Request req, object userState) {
            if ((this.addGoalEventOperationCompleted == null)) {
                this.addGoalEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddGoalEventOperationCompleted);
            }
            this.InvokeAsync("addGoalEvent", new object[] {
                        req}, this.addGoalEventOperationCompleted, userState);
        }
        
        private void OnaddGoalEventOperationCompleted(object arg) {
            if ((this.addGoalEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addGoalEventCompleted(this, new addGoalEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService", IsNullable=false)]
    public partial class DebuggingInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string debugLogField;
        
        /// <remarks/>
        public string debugLog {
            get {
                return this.debugLogField;
            }
            set {
                this.debugLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public partial class Response {
        
        private string[] messagesField;
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", IsNullable=true)]
        public string[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public partial class Request {
        
        private string campaignIdField;
        
        private string contactIdField;
        
        private string emailField;
        
        private System.Nullable<int> engagementValueField;
        
        private bool engagementValueFieldSpecified;
        
        private string goalNameField;
        
        private string iPAddressField;
        
        private string pageNameField;
        
        private string profileField;
        
        private System.Nullable<System.DateTime> timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> engagementValue {
            get {
                return this.engagementValueField;
            }
            set {
                this.engagementValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool engagementValueSpecified {
            get {
                return this.engagementValueFieldSpecified;
            }
            set {
                this.engagementValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string goalName {
            get {
                return this.goalNameField;
            }
            set {
                this.goalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pageName {
            get {
                return this.pageNameField;
            }
            set {
                this.pageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public partial class LogInfo {
        
        private LogCategory categoryField;
        
        private LogCategoryLevel levelField;
        
        /// <remarks/>
        public LogCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public LogCategoryLevel level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public enum LogCategory {
        
        /// <remarks/>
        Db,
        
        /// <remarks/>
        Workflow,
        
        /// <remarks/>
        Validation,
        
        /// <remarks/>
        Callout,
        
        /// <remarks/>
        Apex_code,
        
        /// <remarks/>
        Apex_profiling,
        
        /// <remarks/>
        Visualforce,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Wave,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public enum LogCategoryLevel {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Finest,
        
        /// <remarks/>
        Finer,
        
        /// <remarks/>
        Fine,
        
        /// <remarks/>
        Debug,
        
        /// <remarks/>
        Info,
        
        /// <remarks/>
        Warn,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionIdField;
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService", IsNullable=false)]
    public partial class CallOptions : System.Web.Services.Protocols.SoapHeader {
        
        private string clientField;
        
        /// <remarks/>
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService", IsNullable=false)]
    public partial class AllowFieldTruncationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private bool allowFieldTruncationField;
        
        /// <remarks/>
        public bool allowFieldTruncation {
            get {
                return this.allowFieldTruncationField;
            }
            set {
                this.allowFieldTruncationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService", IsNullable=false)]
    public partial class DebuggingHeader : System.Web.Services.Protocols.SoapHeader {
        
        private LogInfo[] categoriesField;
        
        private LogType debugLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categories")]
        public LogInfo[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public LogType debugLevel {
            get {
                return this.debugLevelField;
            }
            set {
                this.debugLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sforce.com/schemas/class/GoalWebService")]
    public enum LogType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Debugonly,
        
        /// <remarks/>
        Db,
        
        /// <remarks/>
        Profiling,
        
        /// <remarks/>
        Callout,
        
        /// <remarks/>
        Detail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void addGoalEventCompletedEventHandler(object sender, addGoalEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addGoalEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addGoalEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591